import Navbar from '@/components/navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/footer';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Seemo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          `${inter.className}`,
          'flex flex-col min-h-screen justify-between max-w-[1440px]  mx-auto'
        )}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
